# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08my.proto\"A\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"W\n\rLoginResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x15\n\rplayGameTimes\x18\x03 \x01(\t\x12\x0e\n\x06scores\x18\x04 \x01(\t\"L\n\x07MsgInfo\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x12\n\ncreateTime\x18\x02 \x01(\t\x12 \n\x08userInfo\x18\x03 \x01(\x0b\x32\x0e.LoginResponseB\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=12
  _LOGINREQUEST._serialized_end=77
  _LOGINRESPONSE._serialized_start=79
  _LOGINRESPONSE._serialized_end=166
  _MSGINFO._serialized_start=168
  _MSGINFO._serialized_end=244
# @@protoc_insertion_point(module_scope)
